evaluatedNetwork=net;
pxdsResults = semanticseg(imdsTest,evaluatedNetwork, ...
    'MiniBatchSize',1, ...
    'WriteLocation',tempdir, ...
    'Verbose',false,...
    'ExecutionEnvironment', 'cpu');

metrics = evaluateSemanticSegmentation(pxdsResults,pxdsTest,'Verbose',false);

metrics.ClassMetrics